os:
  - linux
language: generic
sudo: required
before_install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - sudo apt-get update
  - sudo apt-get install -y apache2-utils

script:
  - swift build -c release
  - .build/release/MothiAB &
  - ab -n 400 -c 121 http://localhost:1337/